development:
  adapter: mysql
  database: cs461_team35
  username: root
  password:
  host: localhost
test:
  adapter: mysql
  database: cs461_team35
  username: root
  password:
  host: localhost
production:
  adapter: mysql
  database: cs461_team35
  username: root
  password:
  host: localhost
